### ISSUE TITLE
back side stencil test

### ISSUE THREAD

**Issue by Lafeu-p** [Insopitus/threejs-clamp-to-ground#1]
Thanks for your code, I don't know why we need to do a stencil test on the back side. Could you please answer it? Thank you very much.

**Comment by Insopitus** [comment]
The trick here is that we do not write anything to the color buffer for the first and second times. It doesn't matter if it is the frontside or the backside. The two combined make the parts you want to render have a non-zero stencil value. So the third rendering will only write colors on these parts.

**Comment by JackXie60** [comment]
Thank you, I see now, there is another problem, that is, when I get too close to the ground, the drawn surface will disappear, it seems to be after entering the shadow volume, what is the reason? Can it be solved

**Comment by Insopitus** [comment]
Yes. It's a limitation of this implementation. I often set the hight of the the volume as low as possible to avoid that.

**Comment by JackXie60** [comment]
Have you ever encountered such a problem, when drawing a relatively complex polygon, when viewed from the side, the rendering results do not meet the expectations。
for example, you can change the shape such as the below.
`
const shape = new Shape([new Vector2(600, 0), new Vector2(1000, 0), new Vector2(1000, 600), new Vector2(-1000, 600), new Vector2(-1000, 0),  new Vector2(-600, 0),  new Vector2(-600, 400)])
`
when i looking from top,everything is fine.
<img width="778" alt="image" src="https://user-images.githubusercontent.com/74998838/206672291-61b40497-a021-4296-854b-4157afbee7d5.png">
but switch to the side view, some wrong was happened.
<img width="462" alt="image" src="https://user-images.githubusercontent.com/74998838/206672647-c0a10aa8-4d90-49e7-9bd9-8bbb505b5e97.png">

you can set the `colorWrite: true`, The problem will be clearer。
Is there a solution to this problem？

**Comment by Insopitus** [comment]
Sorry for the late reply.

It seems like this approach has trouble rendering concave polygons. I have no idea how to fix it. 

I'll do some research in my spare time, but I'm not sure if there is a solution.

**Comment by Insopitus** [comment]
Hi, I fixed this issue in the latest updates. Check it out if you're still interested.
